config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  resources :lists, except: :destroy do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
  resources :lists, only: [:destroy], as: :list_destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 5 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @movie = Movie.find(params[:bookmark][:movie_id])

    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.movie = @movie
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie, :list)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = Bookmark.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      redirect_to lists_path
    end
    #   if @list.save
    #     redirect_to lists_path
    #   else
    #     render :new
    #   end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="banner_small mb-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1505775561242-727b7fba20f0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80);">
  <div class="container">
    <h1> Create a new bookmark in the list : <%= @list.name %></h1>
    <p>Choose wisely</p>

    <%= link_to 'Back to the lists', lists_path, class:"btn btn-light" %>
  </div>
</div>



<div class="container">

  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.button :submit %>
  <% end %>



<p class="mt-5">Lorem ipsum dolor sit amet consectetur, adipisicing elit.
Illo voluptatem dolor voluptate voluptatum fugit deserunt cumque dolores itaque expedita exercitationem.
Cupiditate facere quisquam vero reiciendis culpa provident explicabo inventore consequatur? </p>


<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit.
Illo voluptatem dolor voluptate voluptatum fugit deserunt cumque dolores itaque expedita exercitationem.
Cupiditate facere quisquam vero reiciendis culpa provident explicabo inventore consequatur? </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright">
        This footer is made with <i class="fas fa-heart"></i> at Le Wagon
      </div>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner mb-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80);">
  <div class="container d-flex align-items justify-content-between">
    <div class="left">
      <h1> Here are my movies lists!</h1>
      <p><span data-controller="typed-js"></span></p>

    </div>

    <div class="right">
      <%= simple_form_for @list do |f| %>
      <%= f.input :name, placeholder: 'Name new list' %>
      <div class="banner-btn">
        <%= f.button :submit %></div>
      </div>
  <% end %>

    </div>



    <div
      class="notification"
      data-controller="notification"
      data-notification-delay-value="2000"
      class="transition transform duration-2000 hidden"
      data-transition-enter-from="opacity-0 translate-x-6"
      data-transition-enter-to="opacity-100 translate-x-0"
      data-transition-leave-from="opacity-100 translate-x-0"
      data-transition-leave-to="opacity-0 translate-x-6"
    >
      <p>This alert will magically disappear!</p>
      <button data-action="notification#hide">Close</button>
    </div>
  </div>
</div>






<div class="container mb-5">
  <div class="row mt-5 d-flex">
    <% @lists.each do |list| %>
      <div class="col-6">
        <div class="card-category m-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.movies.first.present? ? list.movies.first.poster_url : 'https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png' %>)">
          <%= link_to list_path(list), class:"link-to" do %>
            <h2><%= list.name %></h2>
            <%= link_to list_destroy_path(list), method: :delete, class: "suppr-btn", data: { confirm: "sure?" } do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="banner_small mb-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1505775561242-727b7fba20f0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80);">
  <div class="container">
    <h1> Create a new list!</h1>
    <p>Choose wisely</p>
    <%= link_to 'Back to the lists', lists_path, class:"btn btn-light" %>
  </div>
</div>


<div class="container">

  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.button :submit%></div>

  <% end %>
</div>

<div>
<p class="mt-5">Lorem ipsum dolor sit amet consectetur, adipisicing elit.
Illo voluptatem dolor voluptate voluptatum fugit deserunt cumque dolores itaque expedita exercitationem.
Cupiditate facere quisquam vero reiciendis culpa provident explicabo inventore consequatur? </p>

<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit.
Illo voluptatem dolor voluptate voluptatum fugit deserunt cumque dolores itaque expedita exercitationem.
Cupiditate facere quisquam vero reiciendis culpa provident explicabo inventore consequatur? </p>

<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit.
Illo voluptatem dolor voluptate voluptatum fugit deserunt cumque dolores itaque expedita exercitationem.
Cupiditate facere quisquam vero reiciendis culpa provident explicabo inventore consequatur? </p>
</div>

app/views/lists/show.html.erb
<div class="banner_small mb-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1478720568477-152d9b164e26?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80);">
  <div class="container">
    <h1> This is the list : <%= @list.name %></h1>
    <p>So many good movies.</p>
    <%= link_to 'Back to the lists', lists_path, class:"btn btn-light" %>
  </div>
</div>


<div class="container">

<%= link_to 'Create a bookmark', new_list_bookmark_path(@list), class: "btn btn-dark" %>


<div class="bookmarks m-5">
  <h2>Your bookmarks</h2>

  <% @list.bookmarks.each do |bookmark| %>
    <div class="card-product mb-2">
      <img src=" <%=bookmark.movie.poster_url %> " />
      <div class="card-product-infos">
        <h2><%= bookmark.movie.title %> </h2>
        <p><%= bookmark.comment %></p>
        <%= link_to bookmark_path(bookmark), method: :delete, class: "suppr-btn", data: { confirm: "Are you sure you want to remove" } do %>
           <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit.
Illo voluptatem dolor voluptate voluptatum fugit deserunt cumque dolores itaque expedita exercitationem.
Cupiditate facere quisquam vero reiciendis culpa provident explicabo inventore consequatur? </p>

</div>